Repository opt-nc/setup-duckdb-action, pull requests merged in 2023-03, with the labels that each got.

#2 :scroll: Switch to MIT license
  LICENSE
Labels: RUN, documentation, quickfix

#14 develop - changes awaiting release
  .github/dependabot.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/release.yml
  artowrks/README.md
  artowrks/social_preview.png
  artowrks/social_rpreview_original.jpg
Labels: RUN

#21 :memo: doc(example) add duckdb-poem.csv
  data/duckdb-poem.csv
Labels: BUILD, documentation, quickfix, communication
