Repository opt-nc/setup-duckdb-action, pull requests merged in 2024-12, with the labels that each got.

#138 docs: changement de la version de duckdb
  README.md
Labels: BUILD, documentation

#122 Develop
  HOW_TO_MAINTAIN.md
  README.md
  dist/index.js
  dist/index.js.map
  dist/licenses.txt
  dist/sourcemap-register.js
  package-lock.json
  package.json
Labels: Alert : dependency update, RUN, released, security

#139 fix: suppression de la version du plugin convetionalcommits
  .github/workflows/release.yml
Labels: BUILD, bug

#140 Develop
  .github/workflows/release.yml
Labels: BUILD, bug
